### ISSUE TITLE
 VBAD-SUM

### ISSUE THREAD

**Issue by waltonfuture** [swaroop-nath/reward-approx-social-choice-opp-summ#1]
Why do you include very-bad-summary in RLHF training? Why not using normal summary data?

**Comment by swaroop-nath** [comment]
Hi there. This is mostly due to a compute limitation. Technically RL algorithms need the policy to explore several trajectories to understand "good" and "bad" ones.

In our setup, we have a 2-step process to obtain the reward. First, [Mistral-7B](https://mistral.ai/news/announcing-mistral-7b/) gives the rating of the opinion summary along $7$ features ($7$ forward passes through the model). An example of a feature is `aspect-coverage` -- indicates what fraction of aspects (of a product) mentioned in the reviews is picked by the summary. Then, a reward model $\varphi$ uses these $7$ features to produce the final reward. Doing this online, during policy gradient updates is very compute-heavy. So, we use an offline buffer of `GOOD`, `SBAD-SUM` and `VBAD-SUM`. These let the model explore several qualities of trajectory, without using heavy compute resources.

Please refer to our [paper](https://arxiv.org/abs/2402.15473) for more detail -- specifically, Section 4.2. Hope it helped :)
